openapi: 3.0.0
info:
  title: VirusTotal API
  version: 1.0.0
servers:
  - url: https://www.virustotal.com/api/v3/
paths:
  /files/{id}:
    get:
      summary: Retrieve information about a file
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: SHA-256, SHA-1 or MD5 identifying the file
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  sha256:
                    type: string
                  sha1:
                    type: string
                  md5:
                    type: string
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
